myApp/urls.py
from django.conf.urls import url
from myApp.views import index, main, productSearch, addProduct, editProduct, deleteSingleProduct, deleteAllProduct, stream
from myApp.tasks import uploadFile
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'myApp/login_user.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'myApp/logged_out.html'}, name='logout'),

    url(r'^main/$', main.as_view(), name='main'),
    url(r'^upload_file/$', uploadFile, name='upload_file'),
    url(r'^product_search/$', productSearch, name='product_search'),

    url(r'^add_product/$', addProduct.as_view(), name='add_product'),
    url(r'^delete_all_product/$', deleteAllProduct.as_view(), name='delete_all_product'),
    url(r'^delete_single_product/(?P<id>\d+)/$', deleteSingleProduct.as_view(), name='delete_single_product'),
    url(r'^edit_product/(?P<id>\d+)/$', editProduct.as_view(), name='edit_product'),

    url(r'^stream/$', stream, name='stream'),

    url(r'^$', index.as_view(), name='index'),
]

product_importer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('myApp.urls', namespace='intro')),
]

myApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

STATUS = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
)

class productdetails(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=120, null=True)
    sku = models.CharField(max_length=120, null=True, unique=True)
    description = models.CharField(max_length=255, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, to_field='id', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=8, choices=STATUS, default='Active')

    def __str__(self):
        return self.sku

myApp/forms.py
from django import forms
from .models import productdetails


class ProductForm(forms.ModelForm):
    class Meta:
        model = productdetails

        fields = [
            'name',
            'sku',
            'description',
            'status'
        ]

        labels = {
            'name': '',
            'sku': '',
            'description': '',
            'status': ''
        }

        widgets = {
            'name': forms.TextInput(
                attrs={'name': 'name', 'class': 'form-control', 'placeholder': 'Name', }),
            'sku': forms.TextInput(
                attrs={'name': 'sku', 'class': 'form-control', 'placeholder': 'SKU', }),
            'description': forms.TextInput(attrs={'name': 'description', 'class': 'form-control', 'placeholder': 'Description'}),
            'status': forms.Select(
                attrs={'name ': 'status ', 'class ': 'form-control ', 'placeholder ': 'Product Status'}),
        }

myApp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect ,HttpResponse
from django.urls import reverse, reverse_lazy
from django import forms
from .forms import ProductForm
from .models import productdetails
import datetime

import json
from django.http import JsonResponse
from django.core import serializers

from django.db.models import Q
from django.contrib import messages
from django.views.decorators.http import require_http_methods

class index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'myApp/index.html')


class main(View):
    def get(self, request, *args, **kwargs):
        form = ProductForm()

        product_details = serializers.serialize('json', productdetails.objects.all())
        product__data = [d['fields'] for d in json.loads(product_details)]
        product_details_id = [d['pk'] for d in json.loads(product_details)]

        data = zip(product_details_id, product__data)

        context = {
            'form'	: form,
            'data'	: data,
            }

        return render(request, 'myApp/main.html', context)


# class uploadFile(View):
#     def post(self, request, *args, **kwargs):
#         user = User.objects.get(id=request.user.id)
#
#         csv_file = request.FILES.get('productfile')
#
#         import pandas as pd
#         df = pd.read_csv(csv_file, index_col=False)
#
#         for index, item in df.iterrows():
#             name = item['name']
#             sku = item['sku']
#             desc = item['description']
#
#             if productdetails.objects.filter(sku=sku).exists():
#                 productdetails.objects.filter(sku=sku).update(name=name,
#                                                               description=desc,
#                                                               created_by=user)
#
#             else:
#                 productdetails.objects.create(name=name,
#                                               sku=sku,
#                                               description=desc,
#                                               created_by=user)
#
#         return render(request, 'myApp/main.html')

def productSearch(request):
    if request.method == 'POST':
        srch = request.POST['search']

        if srch:
            match = productdetails.objects.filter(Q(sku__icontains=srch) | Q(name__icontains=srch) |
                                                  Q(description__icontains=srch) | Q(status=srch))

            if match:
                form = ProductForm()
                product_details = serializers.serialize('json', match)
                product__data = [d['fields'] for d in json.loads(product_details)]
                product_details_id = [d['pk'] for d in json.loads(product_details)]

                data = zip(product_details_id, product__data)

                context = {
                    'srch': data,
                    'form': form,
                }
                return render(request, 'myApp/main.html', context)
            else:
                messages.error(request, 'No Result Found.')

        else:
            return render(request, 'myApp/main.html')

    return render(request, 'myApp/main.html')

class addProduct(View):
    def post(self, request, *args, **kwargs):
        form = ProductForm(self.request.POST)
        if form.is_valid():
            fform = form.save()
            productdetails.objects.filter(product_id=fform.product_id).update(created_by=request.user.id)

        return redirect('intro:main')


class editProduct(View):
    def get(self, request, *args, **kwargs):
        product_id = kwargs['id']

        form = ProductForm(instance=productdetails.objects.get(product_id=product_id))
        context = {
            'product_id': product_id,
            'form': form}

        return render(request, 'myApp/product_edit.html', context)


    def post(self, request, *args, **kwargs):
        product_id = kwargs['id']

        form = ProductForm(self.request.POST, instance=productdetails.objects.get(product_id=product_id))
        if form.is_valid():
            form.save()
        return redirect('intro:main')

class deleteSingleProduct(View):
    def get(self, request, *args, **kwargs):
        product_id = kwargs['id']
        productdetails.objects.filter(product_id=product_id).delete()

        return redirect('intro:main')

class deleteAllProduct(View):
    def get(self, request, *args, **kwargs):
        productdetails.objects.all().delete()

        return redirect('intro:main')

def stream(request):
    return HttpResponse(
        'data: The server time is: %s\n\n' % datetime.datetime.now(),
        content_type='text/event-stream'
    )

myApp/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Product Importer System</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

    {% block content %}
    {% endblock content %}

    
    <script   src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

myApp/templates/myApp/index.html
{% extends "myApp/base.html" %} {% block content %}
<center>
	<br>
	<br>
	<br>
    <h1>Welcome to Inventory Management System</h1>
    <br>
    <br>
    <h3 style="color:blue;">Click on Login to login to Inventory Management System</h3>
    <br>
    <br>
    <br>
    <a href="{%url 'intro:login'%}"><input type="button" name="" value="LOGIN"></a>
</center>
{% endblock content %}

myApp/templates/myApp/logged_out.html
{% extends "myApp/base.html" %} {% block content %}
<center>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>You have successfully logged out.
    <a href="{%url 'intro:index' %}">Home</a></h1>
</center>
{% endblock content %}

myApp/templates/myApp/login_user.html
{% extends "myApp/base.html" %}

{% block content %}
<div class="container align-center">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
        <form method="POST">
            {% csrf_token %}
            <p>
                <label>Username</label>
                <input type="text" name="username">
            </p>
            <p>
                <label>Password</label>
                <input type="password" name="password">
            </p>
            <button type="submit">Login</button>
        </form>
        <br>
        <br>
        <br>
        <a href="{%url 'intro:index' %}">
            <input type="button" value="BACK">
        </a>
    </center>
</div>
{% endblock content %}

myApp/templates/myApp/main.html
{% extends "myApp/base.html" %} {% block content %}
<center>
    <br>
    <br>
    <br>
<div class="row">
  <div class="col-lg-2">
      <input type="button" name="" value="Add Product" data-toggle="modal" data-target="#myModal">
  </div>
  <div class="col-lg-2">
      <a href="{%url 'intro:delete_all_product'%}"><input type="button" name="" value="Delete All Product"></a>
  </div>
  <div class="col-lg-2">
      <a href="{%url 'intro:main'%}"><input type="button" name="" value="RESET"></a>
  </div>
  <div class="col-lg-4">
      <form action="{%url 'intro:upload_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="productfile">
        <button type="submit">Upload</button>
      </form>
  </div>
    <div class="col-lg-2">
        <a href="{%url 'intro:logout' %}"><input type="button" name="" value="Logout"></a>
    </div>
</div>

<!-- Product Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Enter Invetory Info</h4>
                        </div>
                        <form action="{%url 'intro:add_product' %}" method="POST">
                            {% csrf_token %}
                            <div class="modal-body">
                                {{ form }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

<br>
<br>
<br>
    <form action="{%url 'intro:product_search' %}" method="POST">
      {% csrf_token %}
      <input id="search_text" type="text" name="search" placeholder="Enter SKU of Product to Search" style="width:500px; text-align:center;" />
      <input class="btn btn-lng btn-danger" id="" type="Submit" value="Search" style="margin-right: 20px;"/>
    </form>
<br>

{% if srch %}
<table class="table table-hover" style="text-align:center;">
  <thead>
    <tr>
        <td>Name</td>
        <td>SKU</td>
        <td>Description</td>
        <td>Status</td>
        <td>Edit</td>
    </tr>
  </thead>
  <tbody>
    {% for product_id,d in srch %}
      <tr>
        <td>{{ d.name }}</td>
        <td>{{ d.sku }}</td>
        <td>{{ d.description }}</td>
          {% if d.status == 'Active' %}
            <td class="btn btn-primary">{{ d.status }}</td>
          {% else %}
            <td class="btn btn-warning">{{ d.status }}</td>
          {% endif %}
        <td>
            <a href="{% url 'intro:edit_product' id=product_id %}">
                <button type="button" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
            </a>
            <a href="{% url 'intro:delete_single_product' id=product_id %}">
                <button type="button" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
            </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<br>
{% if not srch %}
<table class="table table-hover" style="text-align:center;">
  <thead>
    <tr>
        <td>Name</td>
        <td>SKU</td>
        <td>Description</td>
        <td>Status</td>
        <td>Edit</td>
    </tr>
  </thead>
  <tbody>
    {% for product_id,d in data %}
      <tr>
        <td>{{ d.name }}</td>
        <td>{{ d.sku }}</td>
        <td>{{ d.description }}</td>
        {% if d.status == 'Active' %}
            <td class="btn btn-primary">{{ d.status }}</td>
          {% else %}
            <td class="btn btn-warning">{{ d.status }}</td>
          {% endif %}
          <td>
            <a href="{% url 'intro:edit_product' id=product_id %}">
                <button type="button" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
            </a>
              <a href="{% url 'intro:delete_single_product' id=product_id %}">
                <button type="button" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
            </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

</center>
{% endblock content %}

myApp/templates/myApp/product_edit.html
{% extends "myApp/base.html" %} {% block content %}
<center>
	<br>
	<br>
	<br>
    
    <a href="{%url 'intro:main'%}"><input type="button" name="" value="BACK"></a>

    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <form action="{%url 'intro:edit_product' id=product_id %}" method="POST">
            {% csrf_token %}

                {{ form }}
            <br>
            <br>
            <br>
                <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
    </div>

</center>
{% endblock content %}